added placeholders and created categories component
fe-sep-22-ooh-team/phone-catalog pull request #9
Opened 2023-01-06 17:17 UTC by yaro-bey

2023-01-06 19:04 UTC, mitattt requested changes
Pls do categories component and slide adaptive. Cause` now out site doent work in correct way

2023-01-07 04:29 UTC, Anna-Shapovalova commented
And please, check the current version. I`ve already done all the additional pages.

2023-01-09 17:29 UTC, Anna-Shapovalova requested changes

2023-01-09 17:29 UTC, Anna-Shapovalova commented on src/components/Slider/Slider.tsx
> +);
Delete this

2023-01-09 17:29 UTC, Anna-Shapovalova commented on src/styles/_mixins.scss
> +  @media (min-width: 1200px) {
this is max-width!!!! It can`t be more than 1200, but the min-width has been correctly identified

2023-01-09 17:29 UTC, Anna-Shapovalova commented on src/modules/HomePage/HomePage.tsx
> +      >
```suggestion
      <div className="
        grid__item--mobile--1-4
        grid__item--tablet--1-9
        grid__item--desktop--1-24"
      >
```

2023-01-09 19:05 UTC, Anna-Shapovalova approved these changes

2023-01-09 19:05 UTC, merged